# Generated by Django 4.1 on 2022-09-01 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(max_length=120)),
                ('dest', models.CharField(max_length=120)),
                ('timing', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
